[package]
name = "complex_number_game"
version = "0.1"
lean_version = "leanprover-community/lean:3.13.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "cbe80ed26d0d8ca6def780e403396b4299fe1fa6"}
